import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
    en: {
        appName: "Coupon Chest",
        welcome: "Welcome to Coupon Chest",
        tagline: "End-to-End Encrypted Coupon Management.",
        login: "Login to Continue",
        loginVault: "Login",
        dashboard: "Dashboard",
        welcomeBack: "Welcome back, {name}",
        vaults: "Your Vaults",
        newVault: "New Vault",
        unlock: "Unlock",
        lock: "Lock",
        password: "Password",
        createVault: "Create Encrypted Vault",
        vaultName: "Vault Name",
        encryptionPassword: "Encryption Password",
        generateKeys: "Generate Keys & Save Vault",
        cancel: "Cancel",
        logout: "Logout",
        privacy: "Privacy Policy",
        terms: "Terms of Use",
        builtWithSecurity: "Built with security first. Your data never leaves your device unencrypted.",
        noVaults: "No vaults found. Create one to get started.",
        addCoupon: "Add Coupon",
        invite: "Invite",
        share: "Share",
        add: "Add",
        saving: "Saving...",
        encrypting: "Encrypting...",
        decrypting: "Decrypting vault content...",
        activityFeed: "Activity Feed",
        noActivity: "No recent activity in this vault.",
        couponMarkedUsed: "Coupon marked used",
        newCouponAdded: "New coupon added",
        undoAvailable: "Undo Available (30d)",
        markUsed: "Mark Used?",
        title: "Title",
        code: "Code",
        value: "Value",
        image: "Image (Optional)",
        protectSave: "Protect & Save",
        enterPassword: "Enter the exact vault password to decrypt and load your records.",
        inviteMember: "Invite Team Member",
        enterEmail: "Enter Gmail address...",
        sendAccess: "Send Access",
        decryptionFailed: "[Decryption Failed]",
        id: "ID",
        delete: "Delete",
        confirmDelete: "Are you sure you want to permanently delete this coupon?",
        moveUp: "Move Up",
        moveDown: "Move Down",
        edit: "Edit",
        formatCode: "Format Code",
        viewCode: "View Details/Code",
        heroTitle: "Your coupons,",
        heroHighlight: "locked & loaded.",
        feature1: "End-to-end encrypted — only you can read your data",
        feature2: "Organize coupons in secure, password-protected vaults",
        feature3: "Share vault access with trusted team members",
        feature4: "Full activity history so nothing gets lost",
        save: "Save",
        rename: "Rename Vault",
        back: "Back to Vaults",
        expirationDate: "Expiration Date (Optional)",
        expiresIn: "Expires in {days}d",
        expired: "Expired",
        expirationWarning: "{count} coupons are expiring soon!",
        shoppingLists: "Shopping Lists",
        newShoppingList: "New List",
        createShoppingList: "Create Shopping List",
        listName: "List Name",
        listNamePlaceholder: "e.g., Weekly Groceries",
        noShoppingLists: "No shopping lists yet. Create one to get started.",
        addItem: "Add Item",
        editItem: "Edit Item",
        itemName: "Item Name",
        itemNamePlaceholder: "e.g., Milk, Eggs, Bread...",
        quantity: "Quantity",
        note: "Note",
        notePlaceholder: "Why didn't you buy it?",
        noItems: "No items in this list.",
        addFirstItem: "Add your first item",
        itemsPending: "items to buy",
        itemsBought: "items bought",
        bought: "Bought",
        markBought: "Mark as bought",
        markPending: "Mark as pending",
        confirmDeleteItem: "Are you sure you want to delete this item?",
        confirmDeleteList: "Are you sure you want to delete this list?",
        create: "Create",
        itemAdded: "Item added",
        itemBought: "Item bought",
        itemDeleted: "Item deleted",
        couponDeleted: "Coupon deleted",
        itemAlreadyExists: "This item already exists in the list!",
        pushNotifications: "Push Notifications",
        notificationsEnabled: "Receive notifications for updates",
        notificationsDisabled: "Enable notifications to receive updates",
        enable: "Enable",
        disable: "Disable",
        notifyNewItem: "New Item Added",
        notifyRemoveItem: "Item Removed",
        notifyUpdateItem: "Item Updated",
        privacyIntro: "At Coupon Chest, your privacy is literally built into the code. We do not store your passwords, private keys, or plain-text coupon data on our servers.",
        privacySection1Title: "1. Data Encryption",
        privacySection1Content: "All sensitive information is encrypted in your browser using standardized Web Crypto APIs before being sent to our backend. We only host the encrypted blobs.",
        privacySection2Title: "2. Authentication",
        privacySection2Content: "We use Netlify Identity to verify your email. We do not sell your personal information to third parties.",
        privacySection3Title: "3. Local Storage",
        privacySection3Content: "We may store your language preference and session tokens in your browser's local storage.",
        termsIntro: "By using Coupon Chest, you agree to the following terms:",
        termsSection1Title: "1. Security Responsibility",
        termsSection1Content: "You are solely responsible for remembering your vault passwords. If you lose your password, there is NO recovery mechanism, and your data will be permanently inaccessible.",
        termsSection2Title: "2. Proper Use",
        termsSection2Content: "You agree not to use this service for storing illegal materials or malicious data.",
        termsSection3Title: "3. No Warranty",
        termsSection3Content: "Coupon Chest is provided \"as is\" without any warranties of any kind.",
    },
    he: {
        appName: "ארגז הקופונים",
        welcome: "ברוכים הבאים לארגז הקופונים",
        tagline: "ניהול קופונים מוצפן מקצה לקצה.",
        login: "התחברו כדי להמשיך",
        loginVault: "כניסה",
        dashboard: "לוח בקרה",
        welcomeBack: "ברוך שובך, {name}",
        vaults: "הכספות שלי",
        newVault: "כספת חדשה",
        unlock: "פתיחה",
        lock: "נעילה",
        password: "סיסמה",
        createVault: "יצירת כספת מוצפנת",
        vaultName: "שם הכספת",
        encryptionPassword: "סיסמת הצפנה",
        generateKeys: "יצירת מפתחות ושמירת כספת",
        cancel: "ביטול",
        logout: "התנתקות",
        privacy: "מדיניות פרטיות",
        terms: "תנאי שימוש",
        builtWithSecurity: "נבנה עם דגש על אבטחה. המידע שלך לעולם לא עוזב את המכשיר ללא הצפנה.",
        noVaults: "לא נמצאו כספות. צרו כספת חדשה כדי להתחיל.",
        addCoupon: "הוספת קופון",
        invite: "הזמנה",
        share: "שיתוף",
        add: "הוספה",
        saving: "שומר...",
        encrypting: "מצפין...",
        decrypting: "מפענח תוכן כספת...",
        activityFeed: "עדכוני פעילות",
        noActivity: "אין פעילות אחרונה בכספת זו.",
        couponMarkedUsed: "קופון סומן כנוצל",
        newCouponAdded: "קופון חדש נוסף",
        undoAvailable: "ביטול זמין (30 יום)",
        markUsed: "לסמן כנוצל?",
        title: "כותרת",
        code: "קוד",
        value: "ערך",
        image: "תמונה (אופציונלי)",
        protectSave: "הצפנה ושמירה",
        enterPassword: "הזינו את סיסמת הכספת המדויקת כדי לפענח ולטעון את הרשומות.",
        inviteMember: "הזמנת חבר צוות",
        enterEmail: "הזינו כתובת ג'ימייל...",
        sendAccess: "שלח גישה",
        decryptionFailed: "[פענוח נכשל]",
        id: "מזהה",
        delete: "מחיקה",
        confirmDelete: "האם אתם בטוחים שברצונכם למחוק את הקופון לצמיתות?",
        moveUp: "הזזה למעלה",
        moveDown: "הזזה למטה",
        edit: "עריכה",
        formatCode: "עצב קוד",
        viewCode: "פרטים / קוד",
        heroTitle: "הקופונים שלך,",
        heroHighlight: "מאובטחים ומוכנים.",
        feature1: "הצפנה מקצה לקצה — רק אתה יכול לקרוא את הנתונים שלך",
        feature2: "ארגן קופונים בכספות מאובטחות עם סיסמה",
        feature3: "שתף גישה לכספת עם חברי צוות מהימנים",
        feature4: "היסטוריית פעילות מלאה כדי שלא תפספס דבר",
        save: "שמירה",
        rename: "שינוי שם הכספת",
        back: "חזרה לכספות",
        expirationDate: "תאריך תפוגה (אופציונלי)",
        expiresIn: "פג בעוד {days} ימים",
        expired: "פג תוקף",
        expirationWarning: "{count} קופונים עומדים לפוג בקרוב!",
        shoppingLists: "רשימות קניות",
        newShoppingList: "רשימה חדשה",
        createShoppingList: "צור רשימת קניות",
        listName: "שם הרשימה",
        listNamePlaceholder: "למשל: קניות שבועיות",
        noShoppingLists: "אין רשימות קניות. צרו רשימה חדשה כדי להתחיל.",
        addItem: "הוסף פריט",
        editItem: "ערוך פריט",
        itemName: "שם הפריט",
        itemNamePlaceholder: "למשל: חלב, ביצים, לחם...",
        quantity: "כמות",
        note: "הערה",
        notePlaceholder: "למה לא קנית את זה?",
        noItems: "אין פריטים ברשימה זו.",
        addFirstItem: "הוסף את הפריט הראשון",
        itemsPending: "פריטים לקנייה",
        itemsBought: "פריטים שנקנו",
        bought: "נקנה",
        markBought: "סמן כנקנה",
        markPending: "סמן כממתין",
        confirmDeleteItem: "האם אתם בטוחים שברצונכם למחוק פריט זה?",
        confirmDeleteList: "האם אתם בטוחים שברצונכם למחוק רשימה זו?",
        create: "צור",
        itemAdded: "פריט נוסף",
        itemBought: "פריט נקנה",
        itemDeleted: "פריט נמחק",
        couponDeleted: "קופון נמחק",
        itemAlreadyExists: "פריט זה כבר קיים ברשימה!",
        pushNotifications: "התראות Push",
        notificationsEnabled: "קבל התראות על עדכונים",
        notificationsDisabled: "הפעל התראות כדי לקבל עדכונים",
        enable: "הפעל",
        disable: "השבת",
        notifyNewItem: "פריט חדש נוסף",
        notifyRemoveItem: "פריט הוסר",
        notifyUpdateItem: "פריט עודכן",
        privacyIntro: "ב-Coupon Chest, הפרטיות שלך בנויה ישירות לתוך הקוד. אנחנו לא שומרים את הסיסמאות שלך, מפתחות פרטיים או נתוני קופונים בטקסט פשוט בשרתים שלנו.",
        privacySection1Title: "1. הצפנת נתונים",
        privacySection1Content: "כל המידע הרגיש מוצפן בדפדפן שלך באמצעות ממשקי Web Crypto סטנדרטיים לפני שהוא נשלח לשרתים שלנו. אנחנו מארחים רק את הנתונים המוצפנים.",
        privacySection2Title: "2. אימות",
        privacySection2Content: "אנחנו משתמשים ב-Netlify Identity כדי לאמת את הדוא\"ל שלך. אנחנו לא מוכרים את המידע האישי שלך לצדדים שלישיים.",
        privacySection3Title: "3. אחסון מקומי",
        privacySection3Content: "אנחנו עשויים לשמור את העדפת השפה שלך ואסימוני הפעלה באחסון המקומי של הדפדפן שלך.",
        termsIntro: "על ידי שימוש ב-Coupon Chest, אתה מסכים לתנאים הבאים:",
        termsSection1Title: "1. אחריות אבטחה",
        termsSection1Content: "אתה האחראי הבלעדי לזכירת סיסמאות הכספת שלך. אם תאבד את הסיסמה שלך, אין מנגנון שחזור, והנתונים שלך יהיו בלתי נגישים לצמיתות.",
        termsSection2Title: "2. שימוש הולם",
        termsSection2Content: "אתה מסכים לא להשתמש בשירות זה לאחסון חומרים לא חוקיים או נתונים זדוניים.",
        termsSection3Title: "3. היעדר אחריות",
        termsSection3Content: "Coupon Chest ניתן \"כפי שהוא\" (as is) ללא כל אחריות מכל סוג שהוא.",
    }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(localStorage.getItem('vault_lang') || 'en');
    const [rtl, setRtl] = useState(lang === 'he');

    useEffect(() => {
        localStorage.setItem('vault_lang', lang);
        setRtl(lang === 'he');
        document.documentElement.dir = lang === 'he' ? 'rtl' : 'ltr';
        document.documentElement.lang = lang;
    }, [lang]);

    const t = (key, params = {}) => {
        let str = translations[lang][key] || translations['en'][key] || key;
        Object.keys(params).forEach(p => {
            str = str.replace(`{${p}}`, params[p]);
        });
        return str;
    };

    const toggleLanguage = () => {
        setLang(prev => prev === 'en' ? 'he' : 'en');
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, toggleLanguage, rtl }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => useContext(LanguageContext);
